dist: xenial
language: python
sudo: false

python:
  - 2.7
  - 3.7

services:
  - postgresql


install:
  - pip install tox codecov

script:
  - tox -e "py${TRAVIS_PYTHON_VERSION//.}"

before_success:
  - coverage erase

after_success:
  - coverage combine
  - codecov
